spring:
  datasource:
    url: jdbc:postgresql://order-db:5432/${DB_NAME}
  kafka:
    bootstrap-servers: kafka:9092
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
server:
  port: 8080
